<template lang="html">
  <div class="tree-list margin-tb-4">
    <ul>
      <tree :node="item" :isLast="index==category_list.length-1" :nodeIndex="{index:index,len:category_list.length}" v-for="(item,index) in category_list" class="tree-root">

      </tree>
    </ul>
  </div>
</template>

<script>

import Tree from './tree'
export default {
  name:'tree-list',
  components:{
    Tree
  },
  data:function(){
    return {
      category_list:[
        {
          name:"搜索记录",
          title:'history',
          kwds:['室内天线','手机','无线基站','室外设备','耗材',"50-100",'天线','手机','基站','无线设备','耗材'],
          children:[]
        },
        {
          name:"子类1",
          children:[
            {
              name:"子类1-1",
              children:[
                {
                  name:'子类1-1-1',
                  children:[]
                },
                {
                  name:'子类1-1-2',
                  children:[]
                },
                {
                  name:'子类1-1-3',
                  children:[]
                }
              ]
            },{
              name:"子类1-2",
              children:[]
            },{
              name:"子类1-3",
              children:[]
            },{
              name:"子类1-4",
              children:[]
            },{
              name:"子类1-5",
              children:[]
            }
          ],
        },{
          name:"子类2",
          children:[
            {
              name:"子类2-1",
              children:[]
            },{
              name:"子类2-2",
              children:[]
            },{
              name:"子类2-3",
              children:[]
            },{
              name:"子类2-4",
              children:[]
            }
          ],
        },{
          name:"子类3",
          children:[
            {
              name:"子类3-1",
              children:[]
            },{
              name:"子类3-2",
              children:[]
            },{
              name:"子类3-3",
              children:[]
            }
          ],
        },{
          name:"子类4",
          children:[
            {
              name:"子类4-1",
              children:[]
            },{
              name:"子类4-2",
              children:[]
            },{
              name:"子类4-3",
              children:[]
            }
          ],
        },{
          name:"子类5",
          children:[
            {
              name:"子类5-1",
              children:[]
            },{
              name:"子类5-2",
              children:[]
            },{
              name:"子类5-3",
              children:[]
            }
          ],
        },{
          name:"子类6",
          children:[
            {
              name:"子类6-1",
              children:[]
            },{
              name:"子类6-2",
              children:[]
            },{
              name:"子类6-3",
              children:[]
            }
          ],
        },{
          name:"子类6",
          children:[
            {
              name:"子类6-1",
              children:[]
            },{
              name:"子类6-2",
              children:[]
            },{
              name:"子类6-3",
              children:[]
            }
          ],
        },{
          name:"子类7",
          children:[
            {
              name:"子类6-1",
              children:[]
            },{
              name:"子类6-2",
              children:[]
            },{
              name:"子类6-3",
              children:[]
            }
          ],
        },{
          name:"子类8",
          children:[
            {
              name:"子类6-1",
              children:[]
            },{
              name:"子类6-2",
              children:[]
            },{
              name:"子类6-3",
              children:[]
            }
          ],
        },{
          name:"子类9",
          children:[
            {
              name:"子类6-1",
              children:[]
            },{
              name:"子类6-2",
              children:[]
            },{
              name:"子类6-3",
              children:[]
            }
          ],
        },{
          name:"子类10",
          children:[
            {
              name:"子类6-1",
              children:[]
            },{
              name:"子类6-2",
              children:[]
            },{
              name:"子类6-3",
              children:[]
            }
          ],
        },{
          name:"子类11",
          children:[
            {
              name:"子类6-1",
              children:[]
            },{
              name:"子类6-2",
              children:[]
            },{
              name:"子类6-3",
              children:[]
            }
          ],
        },
      ]
    }
  }
}
</script>

<style lang="css">

</style>
